data-dir: /opt/pandoc
from: markdown
listings: true
dpi: 75
variables:
  lang: de
  titlepage-text-color: "00aaaa"
  titlepage-rule-color: "aa00aa"
  titlepage-rule-height: 0
  titlepage-background: "Template/Backgrounds/background2.pdf"
  page-background: "Template/Backgrounds/background2.pdf"
  fontsize: 10pt
  toc-own-page: true
  footnotes-pretty: true
  table-use-row-colors: true
  table-row-color: "22FFFF"
  table-row-height: 142pt
  table-column-color: "22FF33"

